### ISSUE TITLE
Code generation UnicodeDecodeError 

### ISSUE THREAD

**Issue by timeisflowing** [alan-turing-institute/CleverCSV#47] opened 2021-09-13 15:40 UTC
UnicodeDecodeError

  'charmap' codec can't decode byte 0x9e in position 1563: character maps to <undefined>

  at /usr/lib/python3.9/encodings/cp1254.py:23 in decode
       19│         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
       20│ 
       21│ class IncrementalDecoder(codecs.IncrementalDecoder):
       22│     def decode(self, input, final=False):
    →  23│         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
       24│ 
       25│ class StreamWriter(Codec,codecs.StreamWriter):
       26│     pass
       27│

**Comment by GjjvdBurg** [comment] 2021-09-16 20:27
Sorry to hear you're getting an error. Can you share the file that gives you the error? It looks like a decoding error that could perhaps be caused by an incorrectly inferred character encoding.

**Comment by timeisflowing** [comment] 2021-09-17 19:21
I came across this error when filtering the data of twint (twitter), although I received it as utf8.. i think there will be no permanent solution, your application works more properly without numeric data and ascii characters. or I have to manually filter the data..

**Comment by GjjvdBurg** [comment] 2021-09-19 17:31
Did the code generated by CleverCSV predict the utf-8 encoding too? We use [chardetect](https://github.com/chardet/chardet) to determine the encoding, so there's not much that can be changed on our end if the encoding prediction is indeed the error.

**Comment by GjjvdBurg** [comment] 2021-09-26 14:15
Closing as the error is likely to be in chardetect, please reopen if there's more to discuss.

**Closed by GjjvdBurg** 2021-09-26 14:15 UTC
