### ISSUE TITLE
Date delimiter prevales on column delimiter

### ISSUE THREAD

**Issue by Mploki** [alan-turing-institute/CleverCSV#52] opened 2022-03-28 15:52 UTC
Hi everyone,

I have a lot of files with long formated dates (with timestamps). The file is delimited by a "," but the timestamps splits hours, minutes, seconds... with a ":".
Example : 
item1,item2,2022-03-28 17:24:10,item4,2022-01-02 22:43:59,item6

I should have : 
Column 1 | Column 2 | Column 3 | Column 4 | Column 5 | Column 6
item1       | item 2       | 22-03...:10| item4       | 22-01...:59| item6
but it gives the following result : 
          C 1                             |C2|              C3                    |C4|  C5
item1,item 2,2022-03-28 17|24|10,item4,2022-01-02 22|43|59,item6

Same thing with some very surprising characters recognised as delimiters when the delimiter is really obvious and more frequent :
 
4819736,lilly354128,fr,Alin,lilly354128,,,,Lilly,DARS,,2 rue des ezda,,4581350,SAINT LA FORET,,FR,+330000000,,,,,,,,,,,,644365,"""LE TEMPS DE DÉCOUVRIR...""","* *COFFRET DÉCOUVERTE SEPT PARFUMS*
On this line, CleverCSV have found a delimiter.... and the delimiter is the star "*" ! I really don't understand the logic ?

I have resolved this issue with a pre-analysis algorithm that verifies, when there are 2 potentials delimiters, if one of them verifies a common formats like, dates, time, adress, floating numbers (coma case). But the annoying thing is that I need to parse two times, one with my pre-analysis and then with CleverCSV.
That could be very nice to have a Clever version for this too.

Have a nice day !

**Comment by GjjvdBurg** [comment] 2022-03-30 22:40
Thanks for raising this issue @Mploki! I'll take a look

**Comment by GjjvdBurg** [comment] 2022-03-30 22:45
Can you share the full example files that show this behavior?

**Comment by Mploki** [comment] 2022-04-01 14:36
@GjjvdBurg I can give you some examples but I have to ask you to keep these files for this work only. They contains some data about a little company transactions. I will obsfuscate some data but I could easily be "unobfuscated". Data will be cut on some points because there is nothing illegal but it's for GDPR purposes

**Comment by GjjvdBurg** [comment] 2022-04-01 22:09
Hi @Mploki, thanks for your help in sorting this out. Please don't share anything that could be of a sensitive nature. One way around this issue could be to remove or obfuscate the fields in the file as much as possible while ensuring that the problem remains. Also, if you'd like, you can email the file to me directly instead of posting it on Github.

**Comment by Mploki** [comment] 2022-04-04 12:24
Hi @GjjvdBurg I can give you at least one obfuscated example. But with a private way. If you can share an email adress in which you want me to send the file that could be a solution.

**Comment by GjjvdBurg** [comment] 2022-04-04 22:30
Thanks @Mploki! You can send it to `gertjanvandenburg at gmail dot com`

**Comment by GjjvdBurg** [comment] 2022-04-11 21:13
Further research indicated this error was due to newlines in non-quoted cells and not because of a bug in CleverCSV. Closing for now but please reopen if the issue is unsolved.

**Closed by GjjvdBurg** 2022-04-11 21:13 UTC
